apiVersion: v1
kind: Service
metadata:
  name: web-server-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80  # Port on which the service will be exposed
      targetPort: 8080  # Port on which the web server container listens
  selector:
    app: web-server